In [1]:
import numpy as np

In [10]:
a = np.zeros((3, 3))

for i in range(3):
    for j in range(3):
        a[i, j] = 0.2*i + 0.3*j
a

array([[0. , 0.3, 0.6],
       [0.2, 0.5, 0.8],
       [0.4, 0.7, 1. ]])

In [7]:
b = np.fft.fft2(a)

In [8]:
b

array([[ 4.5 +0.00000000e+00j, -1.35+7.79422863e-01j,
        -1.35-7.79422863e-01j],
       [-0.9 +5.19615242e-01j,  0.  -7.43708407e-18j,
         0.  +1.03585218e-16j],
       [-0.9 -5.19615242e-01j,  0.  -1.03585218e-16j,
         0.  +7.43708407e-18j]])

In [9]:
np.fft.ifft2(b)

array([[0. +0.j, 0.3+0.j, 0.6+0.j],
       [0.2+0.j, 0.5+0.j, 0.8+0.j],
       [0.4+0.j, 0.7+0.j, 1. +0.j]])

In [11]:
a_val = 1.0 + 0.5j
2*a_val

(2+1j)

In [2]:
a = np.ones([3, 4])
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])